[package]
name = "graphox-codegen"
version = "0.1.0"
edition = "2024"
license.workspace = true

[features]
default = []

[dependencies]
graphox-core = { path = "../graphox-core" }
apollo-compiler = { workspace = true }
ahash = { workspace = true }
dashmap = { workspace = true }
colored = { workspace = true }
serde = { workspace = true }
sonic-rs = { workspace = true }
log = { workspace = true }
pathdiff = { workspace = true }

[dev-dependencies]
ntest = "0.9"
