[package]
name = "graphql-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
apollo-compiler = "1.31"
clap = { version = "4.5", features = ["derive"] }
dashmap = "6"
ropey = "1.6"
serde_json = "1.0.149"
tokio = { version = "1.49.0", features = ["full"] }
tower-lsp = { version = "0.20.0" }
tree-sitter = "0.26"
tree-sitter-graphql = "0.1"
tree-sitter-typescript = "0.23.2"
pathdiff = "0.2"
notify = "8.0.0"
notify-debouncer-mini = "0.6"
ignore = "0.4"
serde = { version = "1.0.228", features = ["derive"] }
serde_yaml = "0.9.34"
glob = "0.3.3"
globset = "0.4.18"
rayon = "1.11.0"
regex = "1.12.2"
fnv = "1.0.7"

[dev-dependencies]
tempfile = "3.24.0"
tower-service = "0.3.3"
criterion = { version = "0.5", features = ["html_reports", "async_tokio"] }
futures-util = "0.3"
tokio-stream = "0.1"

[[bench]]
name = "processing"
harness = false

[[bench]]
name = "lsp_actions"
harness = false
