[package]
name = "graphox-swc-plugin"
version = "0.5.3"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
pathdiff = { workspace = true }
swc_core = { version = "56.0.0", features = [
  "common",
  "ecma_ast",
  "ecma_visit",
  "ecma_utils",
  "ecma_plugin_transform",
  "ecma_parser",
  "ecma_codegen",
] }

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[dev-dependencies]
tempfile = "3.24.0"
ntest = "0.9"
serde_json = { workspace = true }
graphox = { path = "../../.." }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(swc_ast_unknown)'] }
