[package]
name = "graphql-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
graphql-core = { path = "../graphql-core" }
graphql-features = { path = "../graphql-features" }
graphql-codegen = { path = "../graphql-codegen" }
clap = { workspace = true, features = ["derive"] }
colored = { workspace = true }
tokio = { workspace = true }
rayon = { workspace = true }
notify = { workspace = true }
notify-debouncer-mini = { workspace = true }
env_logger = { workspace = true }
ahash = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
apollo-compiler = { workspace = true }
pathdiff = { workspace = true }
glob = { workspace = true }
globset = { workspace = true }
regex = { workspace = true }
once_cell = { workspace = true }
sonic-rs = { workspace = true }
tower-lsp = { workspace = true }
