[package]
name = "graphox-cli"
version = "0.1.0"
edition = "2024"
license.workspace = true
publish.workspace = true

[dependencies]
graphox-core = { path = "../graphox-core" }
graphox-features = { path = "../graphox-features" }
graphox-codegen = { path = "../graphox-codegen" }
colored = { workspace = true }
tokio = { workspace = true }
rayon = { workspace = true }
ignore = { workspace = true }
notify = { workspace = true }
notify-debouncer-mini = { workspace = true }
ahash = { workspace = true }
apollo-compiler = { workspace = true }
pathdiff = { workspace = true }
sonic-rs = { workspace = true }
tower-lsp = { workspace = true }

[dev-dependencies]
ntest = "0.9"
