[package]
name = "graphox-lsp"
version = "0.1.0"
edition = "2024"
license.workspace = true
publish.workspace = true

[dependencies]
graphox-core = { path = "../graphox-core" }
graphox-features = { path = "../graphox-features" }
graphox-codegen = { path = "../graphox-codegen" }
apollo-compiler = { workspace = true }
tower-lsp-server = { workspace = true }
tokio = { workspace = true }
dashmap = { workspace = true }
rayon = { workspace = true }
serde_json = { workspace = true }
log = { workspace = true }
ahash = { workspace = true }
tree-sitter = { workspace = true }
tree-sitter-graphql = { workspace = true }
url = { workspace = true }
ignore = { workspace = true }
pathdiff = { workspace = true }

[dev-dependencies]
ntest = "0.9"
tempfile = "3.24.0"
