[package]
name = "graphox-core"
version = "0.1.0"
edition = "2024"

[features]
default = []

[dependencies]
apollo-compiler = { workspace = true }
ropey = { workspace = true }
serde = { workspace = true }
sonic-rs = { workspace = true }
tree-sitter = { workspace = true }
tree-sitter-graphql = { workspace = true }
tree-sitter-typescript = { workspace = true }
pathdiff = { workspace = true }
ahash = { workspace = true }
once_cell = { workspace = true }
yaml-rust2 = { workspace = true }
log = { workspace = true }
dashmap = { workspace = true }
rayon = { workspace = true }
regex = { workspace = true }
glob = { workspace = true }
globset = { workspace = true }
ignore = { workspace = true }
url = { workspace = true }
lsp-types = { workspace = true }
colored = { workspace = true }
dirs = { workspace = true }

[dev-dependencies]
ntest = "0.9"
tempfile = "3.24.0"
