/**
 * SWC GraphQL Plugin - Node.js WASM Wrapper
 * 
 * This package provides a convenient Node.js interface to the SWC GraphQL plugin.
 * The actual transformation logic is implemented in Rust and compiled to WASM.
 * 
 * @example
 * // rsbuild.config.ts
 * import { defineConfig } from '@rsbuild/core';
 * import { createSWCPlugin } from '@soundtrack/graphox-swc';
 * 
 * export default defineConfig({
 *   tools: {
 *     swc: {
 *       jsc: {
 *         experimental: {
 *           plugins: [
 *             createSWCPlugin({
 *               manifestPath: './__generated__/manifest.json',
 *               outputDir: './__generated__'
 *             })
 *           ]
 *         }
 *       }
 *     }
 *   }
 * });
 */

import * as path from 'path';
import * as fs from 'fs';

/**
 * Configuration options for the SWC GraphQL plugin.
 */
export interface PluginConfig {
  /**
   * Path to the manifest.json file generated by graphox codegen.
   * The manifest maps GraphQL source code to generated document files.
   */
  manifestPath?: string;
  
  /**
   * Inline manifest data. Can be used instead of manifestPath.
   * Takes precedence over manifestPath if both are provided.
   */
  manifestData?: Array<{
    source: string;
    path: string;
    name: string;
  }>;
  
  /**
   * Directory where generated files are located.
   * Used for resolving relative paths and detecting imports.
   */
  outputDir: string;
  
  /**
   * Additional import paths to treat as GraphQL entrypoints.
   * Useful for path aliases like '@/graphql'.
   */
  graphqlImportPaths?: string[];
}

/**
 * Get the path to the WASM plugin.
 * 
 * The WASM file is built from the Rust source in ../rust/
 * and bundled with this package.
 */
function getWasmPath(): string {
  // The WASM file should be in the wasm/ directory after building
  const wasmPath = path.join(__dirname, '..', 'wasm', 'graphox_swc_plugin.wasm');
  
  if (!fs.existsSync(wasmPath)) {
    throw new Error(
      `WASM plugin not found at ${wasmPath}. ` +
      'Run "pnpm run build:wasm" to build the plugin.'
    );
  }
  
  return wasmPath;
}

/**
 * Create a SWC plugin configuration.
 * 
 * Returns a tuple [wasmPath, options] that can be passed directly to SWC's
 * experimental plugins configuration.
 * 
 * @example
 * const plugin = createSWCPlugin({
 *   manifestPath: './__generated__/manifest.json',
 *   outputDir: './__generated__'
 * });
 * 
 * // Use with SWC
 * const result = await transform(code, {
 *   jsc: {
 *     experimental: {
 *       plugins: [plugin]
 *     }
 *   }
 * });
 */
export function createSWCPlugin(config: PluginConfig): [string, PluginConfig] {
  // Validate required fields first
  if (!config.outputDir) {
    throw new Error('outputDir is required in PluginConfig');
  }
  
  const wasmPath = getWasmPath();
  
  // Return tuple for SWC
  return [wasmPath, config];
}

/**
 * Validate that the WASM plugin is available.
 * 
 * @returns true if WASM is built and available
 */
export function isWasmAvailable(): boolean {
  try {
    getWasmPath();
    return true;
  } catch {
    return false;
  }
}

/**
 * Load the manifest from disk or return inline data.
 * 
 * @param config - Plugin configuration
 * @returns Parsed manifest entries
 */
export function loadManifest(config: PluginConfig): Array<{ source: string; path: string; name: string }> {
  if (config.manifestData) {
    return config.manifestData;
  }
  
  if (config.manifestPath && fs.existsSync(config.manifestPath)) {
    const content = fs.readFileSync(config.manifestPath, 'utf-8');
    const data = JSON.parse(content);
    return data.entries || [];
  }
  
  return [];
}

// Default export
export default createSWCPlugin;
