/**
 * SWC GraphQL Plugin - Node.js WASM Wrapper
 * 
 * This package provides a convenient Node.js interface to the SWC GraphQL plugin.
 * The actual transformation logic is implemented in Rust and compiled to WASM.
 * 
 * @example
 * // rsbuild.config.ts
 * import { defineConfig } from '@rsbuild/core';
 * import { createSWCPlugin } from '@graphox/swc-plugin';
 * 
 * export default defineConfig({
 *   tools: {
 *     swc: {
 *       jsc: {
 *         experimental: {
 *           plugins: [
 *             createSWCPlugin({
 *               manifestPath: './__generated__/manifest.json',
 *               outputDir: './__generated__'
 *             })
 *           ]
 *         }
 *       }
 *     }
 *   }
 * });
 */

import * as path from 'path';
import * as fs from 'fs';
import { fileURLToPath } from 'url';
import * as jsonc from 'jsonc-parser';

/**
 * Robust way to get __dirname equivalent in both CJS and ESM.
 */
// @ts-ignore
const _dirname = typeof import.meta.url !== 'undefined'
  ? path.dirname(fileURLToPath(import.meta.url))
  : __dirname;

/**
 * One codegen output directory, i.e. one graphox project.
 *
 * Register every output a build resolves against in a single plugin instance.
 * SWC serializes the whole AST across the wasm boundary per plugin per module,
 * so N instances cost N round-trips on every file while N-1 of them can do
 * nothing — a module belongs to exactly one output.
 */
export interface OutputConfig {
  /** Directory where this project's generated files live. */
  outputDir: string;

  /** See {@link PluginConfig.manifestPath}. */
  manifestPath?: string;

  /** See {@link PluginConfig.manifestData}. */
  manifestData?: Array<{ source: string; path: string; name: string }>;

  /** See {@link PluginConfig.graphqlImportPaths}. */
  graphqlImportPaths?: string[];

  /**
   * Bare specifier other projects use to import this output, e.g.
   * `@soundtrack/playback/graphql`. A document here imported from another
   * package is rewritten to `<importAlias>/<codegen file>`, because a relative
   * path would reach past the package's subpath exports.
   *
   * Inferred from the owning package's `name` and `exports`. Set it explicitly
   * when that cannot be worked out — a package with no `exports` field, or one
   * resolved through bundler aliases only.
   */
  importAlias?: string;

  /**
   * Root of the package owning this output. Modules inside it import these
   * documents by relative path; anything outside goes through `importAlias`.
   *
   * Inferred as the directory of the nearest `package.json`.
   */
  packageRoot?: string;
}

/**
 * Configuration options for the SWC GraphQL plugin.
 */
export interface PluginConfig {
  /**
   * Every output this instance resolves against. Preferred over the
   * single-output fields below, which remain for backwards compatibility.
   */
  outputs?: OutputConfig[];

  /** See {@link OutputConfig.importAlias}. Single-output form. */
  importAlias?: string;

  /** See {@link OutputConfig.packageRoot}. Single-output form. */
  packageRoot?: string;

  /**
   * Path to the manifest.json file generated by graphox codegen.
   * The manifest maps GraphQL source code to generated document files.
   */
  manifestPath?: string;
  
  /**
   * Inline manifest data. Can be used instead of manifestPath.
   * Takes precedence over manifestPath if both are provided.
   */
  manifestData?: Array<{
    source: string;
    path: string;
    name: string;
  }>;
  
  /**
   * Directory where generated files are located.
   * Used for resolving relative paths and detecting imports.
   *
   * Deprecated single-output form; equivalent to a one-element `outputs`.
   */
  outputDir?: string;
  
  /**
   * Additional import paths to treat as GraphQL entrypoints.
   * Useful for path aliases like '@/graphql'.
   */
  graphqlImportPaths?: string[];

  /**
   * File extension to append to generated import paths.
   * Options: "Ts", "Dts", "Js" or None (default)
   */
  emitExtensions?: 'Ts' | 'Dts' | 'Js' | 'None';
}

/**
 * Get the path to the WASM plugin.
 * 
 * The WASM file is built from the Rust source in ../rust/
 * and bundled with this package.
 */
function getWasmPath(): string {
  // Allow overriding the WASM plugin path via environment variable
  if (process.env.GRAPHOX_SWC_PLUGIN_PATH) {
    const overridePath = path.resolve(process.env.GRAPHOX_SWC_PLUGIN_PATH);
    if (fs.existsSync(overridePath)) {
      return overridePath;
    }
    console.warn(`GRAPHOX_SWC_PLUGIN_PATH is set but file not found at ${overridePath}. Falling back to default.`);
  }

  // The WASM file is built using cargo build --target wasm32-wasip1
  // and placed in the wasm/ directory.
  const wasmPath = path.join(_dirname, '..', 'wasm', 'graphox_swc_plugin.wasm');
  
  if (!fs.existsSync(wasmPath)) {
    throw new Error(
      `WASM plugin not found at ${wasmPath}. ` +
      'Run "pnpm run build:wasm" to build the plugin.'
    );
  }
  
  return wasmPath;
}

function findNearestFile(startDir: string, filename: string): string | null {
  let currentDir = startDir;
  while (currentDir) {
    const filePath = path.join(currentDir, filename);
    if (fs.existsSync(filePath)) {
      return filePath;
    }
    const parentDir = path.dirname(currentDir);
    if (parentDir === currentDir) {
      break;
    }
    currentDir = parentDir;
  }
  return null;
}

function stripScriptExtension(filePath: string): string {
  return filePath.replace(/(\.d)?\.(mjs|cjs|js|jsx|ts|tsx)$/, '');
}

function resolveTsConfigPaths(tsconfigPath: string, absoluteOutputDir: string): string[] {
  try {
    const content = fs.readFileSync(tsconfigPath, 'utf8');
    const tsconfig = jsonc.parse(content);
    const paths = tsconfig?.compilerOptions?.paths;
    if (!paths) return [];

    const baseUrl = tsconfig.compilerOptions.baseUrl 
      ? path.resolve(path.dirname(tsconfigPath), tsconfig.compilerOptions.baseUrl) 
      : path.dirname(tsconfigPath);
    
    const matchedPaths: string[] = [];
    const absoluteEntrypointPath = path.join(absoluteOutputDir, 'graphql');
    const absoluteIndexPath = path.join(absoluteOutputDir, 'index');

    const absOutNoExt = stripScriptExtension(absoluteOutputDir);
    const absEntryNoExt = stripScriptExtension(absoluteEntrypointPath);
    const absIndexNoExt = stripScriptExtension(absoluteIndexPath);

    for (const [alias, targets] of Object.entries(paths) as [string, string[]][]) {
      for (const target of targets) {
        const cleanTarget = target.replace(/\*$/, '');
        const absTarget = path.resolve(baseUrl, cleanTarget);
        const absTargetNoExt = stripScriptExtension(absTarget);

        if (absTargetNoExt === absOutNoExt) {
           let a = alias.replace(/\*$/, '');
           if (!a.endsWith('/')) a += '/';
           matchedPaths.push(a);
           continue;
        }

        if (absTargetNoExt === absEntryNoExt || 
            absTargetNoExt === absIndexNoExt ||
            stripScriptExtension(path.join(absTargetNoExt, 'index')) === absIndexNoExt) {
           matchedPaths.push(alias.replace(/\*$/, ''));
        }
      }
    }
    return matchedPaths;
  } catch (e) {
    console.debug(`resolveTsConfigPaths error for ${tsconfigPath}:`, e);
    return [];
  }
}

function resolvePackageJsonImports(pkgJsonPath: string, absoluteOutputDir: string): string[] {
  try {
    const content = fs.readFileSync(pkgJsonPath, 'utf8');
    const pkg = JSON.parse(content);
    const imports = pkg.imports;
    if (!imports) return [];

    const matchedImports: string[] = [];
    const pkgDir = path.dirname(pkgJsonPath);
    const absoluteEntrypointPath = path.join(absoluteOutputDir, 'graphql');
    const absoluteIndexPath = path.join(absoluteOutputDir, 'index');

    const absOutNoExt = stripScriptExtension(absoluteOutputDir);
    const absEntryNoExt = stripScriptExtension(absoluteEntrypointPath);
    const absIndexNoExt = stripScriptExtension(absoluteIndexPath);
    
    function checkTarget(target: unknown, alias: string) {
       if (typeof target !== 'string') return;
       const absTarget = path.resolve(pkgDir, target);
       const absTargetNoExt = stripScriptExtension(absTarget);
       
       if (absTargetNoExt === absOutNoExt) {
         let a = alias.replace(/\*$/, '');
         if (!a.endsWith('/')) a += '/';
         matchedImports.push(a);
         return;
       }

       if (absTargetNoExt === absEntryNoExt || 
           absTargetNoExt === absIndexNoExt ||
           stripScriptExtension(path.join(absTargetNoExt, 'index')) === absIndexNoExt) {
         matchedImports.push(alias.replace(/\*$/, ''));
       }
    }

    for (const [alias, target] of Object.entries(imports)) {
      if (typeof target === 'string') {
        checkTarget(target, alias);
      } else if (typeof target === 'object' && target !== null) {
        for (const key of ['import', 'types', 'default', 'require']) {
          const val = (target as Record<string, any>)[key];
          if (val) {
             checkTarget(val, alias);
          }
        }
      }
    }
    
    return matchedImports;
  } catch (e) {
    console.debug(`resolvePackageJsonImports error for ${pkgJsonPath}:`, e);
    return [];
  }
}

/**
 * Load the manifest from disk or return inline data.
 * 
 * @param config - Plugin configuration
 * @returns Parsed manifest entries
 */
export function loadManifest(
  config: Pick<OutputConfig, 'manifestPath' | 'manifestData'> & { outputDir?: string }
): Array<{ source: string; path: string; name: string }> {
  if (config.manifestData) {
    return config.manifestData;
  }

  const manifestPath =
    config.manifestPath ||
    (config.outputDir ? path.join(path.resolve(config.outputDir), 'manifest.json') : undefined);

  if (manifestPath && fs.existsSync(manifestPath)) {
    try {
      const content = fs.readFileSync(manifestPath, 'utf-8');
      const data = JSON.parse(content);
      return Array.isArray(data) ? data : (data.entries || []);
    } catch (e) {
      // Ignore errors reading manifest
    }
  }
  
  return [];
}

/**
 * The bare specifier prefix other packages use to reach `absoluteOutputDir`,
 * derived from the owning package's `name` and `exports`.
 *
 * `canServeDeep` reports whether the exports map can also serve files *inside*
 * that subpath. Cross-project document imports are rewritten to
 * `<alias>/<codegen file>`, so without a wildcard entry the rewritten specifier
 * would be blocked by the exports map at bundle time.
 *
 * Deliberately conservative: it only reports an alias when exactly one subpath
 * matches. A wrong guess here produces a plausible specifier that fails to
 * resolve during the build, which is a worse failure than asking for config.
 */
export function resolvePackageExportAlias(
  pkgJsonPath: string,
  absoluteOutputDir: string
): { alias: string; subpath: string; canServeDeep: boolean } | null {
  try {
    const pkg = JSON.parse(fs.readFileSync(pkgJsonPath, 'utf8'));
    if (!pkg.name || !pkg.exports || typeof pkg.exports !== 'object') return null;

    const pkgDir = path.dirname(pkgJsonPath);
    const outNoExt = stripScriptExtension(absoluteOutputDir);
    const entryNoExt = stripScriptExtension(path.join(absoluteOutputDir, 'graphql'));
    const indexNoExt = stripScriptExtension(path.join(absoluteOutputDir, 'index'));

    // Condition keys in preference order; arrays and null targets are skipped
    // rather than guessed at.
    const targetsOf = (target: unknown): string[] => {
      if (typeof target === 'string') return [target];
      if (target && typeof target === 'object' && !Array.isArray(target)) {
        return ['import', 'types', 'default', 'require']
          .map((key) => (target as Record<string, unknown>)[key])
          .filter((value): value is string => typeof value === 'string');
      }
      return [];
    };

    const matches: Array<{ subpath: string }> = [];
    let canServeDeep = false;

    for (const [subpath, target] of Object.entries(pkg.exports)) {
      if (!subpath.startsWith('.')) continue; // conditions-only root form

      for (const raw of targetsOf(target)) {
        const abs = path.resolve(pkgDir, raw.replace(/\*/g, ''));
        const absNoExt = stripScriptExtension(abs);

        if (subpath.includes('*')) {
          // e.g. "./graphql/*": "./graphql/*" — serves files in the directory.
          const prefix = stripScriptExtension(path.resolve(pkgDir, raw.split('*')[0]));
          if (prefix === outNoExt || prefix === path.join(outNoExt, path.sep)) {
            canServeDeep = true;
          }
          continue;
        }

        if (
          absNoExt === entryNoExt ||
          absNoExt === indexNoExt ||
          absNoExt === outNoExt ||
          stripScriptExtension(path.join(absNoExt, 'index')) === indexNoExt
        ) {
          matches.push({ subpath });
        }
      }
    }

    const unique = Array.from(new Set(matches.map((m) => m.subpath)));
    if (unique.length !== 1) return null;

    const subpath = unique[0];
    const alias = subpath === '.' ? pkg.name : `${pkg.name}/${subpath.replace(/^\.\//, '')}`;
    return { alias, subpath, canServeDeep };
  } catch {
    return null;
  }
}

// Caching for expensive path resolutions
const importPathsCache = new Map<string, string[]>();

/**
 * Create a SWC plugin configuration.
 * 
 * Returns a tuple [wasmPath, options] that can be passed directly to SWC's
 * experimental plugins configuration.
 */
/** Resolve one output: absolute paths, aliases, package root, manifest. */
function resolveOutput(
  output: OutputConfig,
  rootDir: string,
  fallbackTsconfig: string | null,
  fallbackPkgJson: string | null,
  warn: (message: string) => void
): Required<Pick<OutputConfig, 'outputDir'>> & OutputConfig {
  const resolvedOutputDir = path.resolve(rootDir, output.outputDir);
  const resolvedManifestPath = output.manifestPath
    ? path.resolve(rootDir, output.manifestPath)
    : path.join(resolvedOutputDir, 'manifest.json');

  const projectTsconfig = findNearestFile(resolvedOutputDir, 'tsconfig.json') || fallbackTsconfig;
  const projectPkgJson = findNearestFile(resolvedOutputDir, 'package.json') || fallbackPkgJson;

  const cacheKey = `${rootDir}:${resolvedOutputDir}`;
  let autoDetectedPaths = importPathsCache.get(cacheKey);
  if (!autoDetectedPaths) {
    autoDetectedPaths = [];
    if (projectTsconfig) {
      for (const p of resolveTsConfigPaths(projectTsconfig, resolvedOutputDir)) {
        if (!autoDetectedPaths.includes(p)) autoDetectedPaths.push(p);
      }
    }
    if (projectPkgJson) {
      for (const p of resolvePackageJsonImports(projectPkgJson, resolvedOutputDir)) {
        if (!autoDetectedPaths.includes(p)) autoDetectedPaths.push(p);
      }
    }
    importPathsCache.set(cacheKey, autoDetectedPaths);
  }

  const graphqlImportPaths = [...autoDetectedPaths];
  for (const p of output.graphqlImportPaths || []) {
    if (!graphqlImportPaths.includes(p)) graphqlImportPaths.push(p);
  }

  // The package owning this output. Modules inside it import by relative path;
  // anything outside has to go through the alias.
  const packageRoot =
    output.packageRoot || (projectPkgJson ? path.dirname(projectPkgJson) : undefined);

  let importAlias = output.importAlias;
  if (!importAlias && projectPkgJson) {
    const inferred = resolvePackageExportAlias(projectPkgJson, resolvedOutputDir);
    if (inferred) {
      importAlias = inferred.alias;
      if (!inferred.canServeDeep) {
        warn(
          `@graphox/swc-plugin: "${inferred.alias}" resolves to ${resolvedOutputDir}, but ` +
            `${projectPkgJson} has no exports entry that can serve files inside it. ` +
            `Documents imported from another package are rewritten to ` +
            `"${inferred.alias}/<file>", which will not resolve. Add ` +
            `"${inferred.subpath}/*": "${inferred.subpath}/*" to its exports.`
        );
      }
    }
  }

  // The alias is also how another project names this entrypoint, so it has to be
  // recognised as one.
  if (importAlias && !graphqlImportPaths.includes(importAlias)) {
    graphqlImportPaths.push(importAlias);
  }

  return {
    ...output,
    outputDir: resolvedOutputDir,
    manifestPath: resolvedManifestPath,
    graphqlImportPaths,
    importAlias,
    packageRoot,
    manifestData: loadManifest({
      manifestPath: resolvedManifestPath,
      manifestData: output.manifestData,
      outputDir: resolvedOutputDir,
    }),
  };
}

/**
 * Output directories must be distinct. Documents, by contrast, may repeat freely
 * across outputs: two projects sharing a document name — or the same source text
 * — is normal, and resolution is scoped to the entrypoint an import came from
 * rather than searched across a merged map, so it stays unambiguous.
 */
function assertOutputsDoNotOverlap(outputs: OutputConfig[]): void {
  for (let i = 0; i < outputs.length; i++) {
    for (let j = i + 1; j < outputs.length; j++) {
      const a = outputs[i].outputDir;
      const b = outputs[j].outputDir;
      if (a === b) {
        throw new Error(`@graphox/swc-plugin: duplicate outputDir "${a}" in outputs.`);
      }
      const nested =
        b.startsWith(a + path.sep) || a.startsWith(b + path.sep);
      if (nested) {
        throw new Error(
          `@graphox/swc-plugin: outputDir "${a}" and "${b}" overlap. Outputs must be ` +
            `distinct so each module belongs to exactly one.`
        );
      }
    }
  }

}

/**
 * Resolve every declared output: absolute paths, inferred alias and package
 * root, inlined manifest. Exported separately from {@link createSWCPlugin} so
 * the resolution can be exercised without a built wasm artifact.
 *
 * Throws if the outputs overlap.
 */
export function resolvePluginOutputs(
  config: PluginConfig,
  options?: { cwd?: string; filename?: string; onWarn?: (message: string) => void }
): OutputConfig[] {
  const declared: OutputConfig[] =
    config.outputs && config.outputs.length > 0
      ? config.outputs
      : [
          {
            outputDir: config.outputDir as string,
            manifestPath: config.manifestPath,
            manifestData: config.manifestData,
            graphqlImportPaths: config.graphqlImportPaths,
            importAlias: config.importAlias,
            packageRoot: config.packageRoot,
          },
        ];

  for (const output of declared) {
    if (!output.outputDir) {
      throw new Error('outputDir is required in PluginConfig');
    }
  }

  const warn = options?.onWarn || ((message: string) => console.warn(message));

  let rootDir = options?.cwd || process.cwd();
  let tsconfigPath: string | null = null;
  let pkgJsonPath: string | null = null;

  if (!options?.cwd && declared.some((output) => !path.isAbsolute(output.outputDir))) {
    const startDir = options?.filename ? path.dirname(path.resolve(options.filename)) : rootDir;
    tsconfigPath = findNearestFile(startDir, 'tsconfig.json');
    pkgJsonPath = findNearestFile(startDir, 'package.json');
    const rootFile = pkgJsonPath || tsconfigPath;
    if (rootFile) {
      rootDir = path.dirname(rootFile);
    }
  }

  const outputs = declared.map((output) =>
    resolveOutput(output, rootDir, tsconfigPath, pkgJsonPath, warn)
  );

  assertOutputsDoNotOverlap(outputs);

  return outputs;
}

/**
 * Create a SWC plugin configuration.
 *
 * Returns a tuple [wasmPath, options] that can be passed directly to SWC's
 * experimental plugins configuration.
 */
export function createSWCPlugin(
  config: PluginConfig,
  options?: { cwd?: string; filename?: string; onWarn?: (message: string) => void }
): [string, PluginConfig] {
  // Outputs first, so a misconfiguration reports itself even when the wasm
  // artifact has not been built yet.
  const outputs = resolvePluginOutputs(config, options);
  const wasmPath = getWasmPath();

  // Manifests are inlined so the wasm guest needs no filesystem access.
  const inlinedConfig: PluginConfig = {
    outputs,
    emitExtensions: config.emitExtensions,
    // Kept for older plugin builds reading the single-output shape.
    outputDir: outputs[0].outputDir,
    graphqlImportPaths: outputs[0].graphqlImportPaths,
    manifestData: outputs[0].manifestData,
  };

  return [wasmPath, inlinedConfig];
}

/**
 * Validate that the WASM plugin is available.
 * 
 * @returns true if WASM is built and available
 */
export function isWasmAvailable(): boolean {
  try {
    getWasmPath();
    return true;
  } catch {
    return false;
  }
}

// Default export
export default createSWCPlugin;
