use crate::document::DocumentState;
use crate::queries::*;
use colored::*;
use lsp_types::*;
use std::path::{Path, PathBuf};
use tree_sitter::StreamingIterator;

pub const SEMANTIC_TOKEN_LEGEND: &[SemanticTokenType] = &[
    SemanticTokenType::VARIABLE,
    SemanticTokenType::TYPE,
    SemanticTokenType::STRING,
    SemanticTokenType::KEYWORD,
    SemanticTokenType::PROPERTY,
    SemanticTokenType::FUNCTION,
    SemanticTokenType::ENUM,
];

pub const DIAGNOSTIC_SOURCE: Option<&'static str> = Some("graphox");

#[repr(u32)]
pub enum SemanticTokenKind {
    Variable = 0,
    Type = 1,
    String = 2,
    Keyword = 3,
    Property = 4,
    Function = 5,
    Enum = 6,
}

pub fn is_relevant_file(path: &Path) -> bool {
    (|| {
        if path
            .components()
            .any(|c| c.as_os_str() == "node_modules" || c.as_os_str() == ".git")
        {
            return false;
        }

        let ext = path.extension().and_then(|s| s.to_str()).unwrap_or("");
        let is_ext_relevant = matches!(
            ext,
            "graphql"
                | "graphqls"
                | "gql"
                | "ts"
                | "tsx"
                | "mts"
                | "cts"
                | "js"
                | "jsx"
                | "mjs"
                | "cjs"
        );

        if !is_ext_relevant {
            return false;
        }

        true
    })()
}

pub fn has_generated_header(content: &str) -> bool {
    content.starts_with("// @generated")
        || content.starts_with("/* @generated */")
        || content.starts_with("// Code generated by")
        || content.starts_with("/** @generated */")
        || content.contains("This file was automatically generated and should not be edited.")
}

pub fn get_glob_root(pattern: &str) -> PathBuf {
    let path = Path::new(pattern);
    let mut root = PathBuf::new();
    let components: Vec<_> = path.components().collect();
    for component in components {
        let s = component.as_os_str().to_str().unwrap_or("");
        if s.contains('*') || s.contains('?') || s.contains('[') || s.contains('{') {
            break;
        }
        // If it looks like a file (has an extension), don't include it in the root
        if Path::new(s).extension().is_some() {
            break;
        }
        root.push(component);
    }
    root
}

pub fn get_project_files(
    include_patterns: &[String],
    exclude_patterns: &[String],
    base_dir: &Path,
    _output_dir: Option<&str>,
) -> Vec<PathBuf> {
    use globset::{Glob, GlobSetBuilder};
    use ignore::WalkBuilder;

    let mut include_builder = GlobSetBuilder::new();
    let mut roots = Vec::new();
    let mut direct_files = Vec::new();

    for p in include_patterns {
        let p_clean = p.strip_prefix("./").unwrap_or(p);

        let is_glob = p_clean.contains('*')
            || p_clean.contains('?')
            || p_clean.contains('[')
            || p_clean.contains('{');

        if !is_glob {
            let path = base_dir.join(p_clean);
            if path.is_file() {
                direct_files.push(path);
                continue;
            }
            if path.is_dir() {
                roots.push(path.clone());
                let mut p_glob = p_clean.to_string();
                if !p_glob.ends_with('/') && !p_glob.is_empty() {
                    p_glob.push('/');
                }
                p_glob.push_str("**/*");
                if let Ok(g) = Glob::new(&p_glob) {
                    include_builder.add(g);
                }
                continue;
            }
        }

        if let Ok(g) = Glob::new(p) {
            include_builder.add(g);
        }
        if p_clean != p
            && let Ok(g) = Glob::new(p_clean)
        {
            include_builder.add(g);
        }

        let root = get_glob_root(p_clean);
        let root_path = if root.as_os_str().is_empty() {
            base_dir.to_path_buf()
        } else {
            base_dir.join(root)
        };
        if root_path.exists() {
            roots.push(root_path);
        }
    }

    let mut exclude_builder = GlobSetBuilder::new();
    for p in exclude_patterns {
        let p_clean = p.strip_prefix("./").unwrap_or(p);
        if let Ok(g) = Glob::new(p_clean) {
            exclude_builder.add(g);
        }
        if p != p_clean
            && let Ok(g) = Glob::new(p)
        {
            exclude_builder.add(g);
        }
    }

    let include_set = include_builder
        .build()
        .unwrap_or_else(|_| GlobSetBuilder::new().build().unwrap());
    let exclude_set = exclude_builder
        .build()
        .unwrap_or_else(|_| GlobSetBuilder::new().build().unwrap());

    let (tx, rx) = std::sync::mpsc::channel();

    if !roots.is_empty() {
        roots.sort();
        let mut unique_roots: Vec<PathBuf> = Vec::new();
        for root in roots {
            if !unique_roots.iter().any(|r| path_starts_with(&root, r)) {
                unique_roots.push(root);
            }
        }

        let mut walk_builder = WalkBuilder::new(&unique_roots[0]);
        for root in &unique_roots[1..] {
            walk_builder.add(root);
        }

        let walk = walk_builder
            .add_custom_ignore_filename(".graphqlignore")
            .hidden(false)
            .follow_links(true)
            .build_parallel();

        let include_set_ref = &include_set;
        let exclude_set_ref = &exclude_set;

        walk.run(|| {
            let tx = tx.clone();
            Box::new(move |entry| {
                if let Ok(entry) = entry
                    && entry.file_type().is_some_and(|ft| ft.is_file())
                {
                    let path = entry.path();
                    if is_relevant_file(path) {
                        let mut matched = include_set_ref.is_match(path)
                            || include_set_ref.is_match(to_posix_path(path));

                        if !matched && let Ok(abs_path) = std::fs::canonicalize(path) {
                            matched = include_set_ref.is_match(&abs_path)
                                || include_set_ref.is_match(to_posix_path(&abs_path));
                        }

                        if !matched && let Some(rel_to_base) = pathdiff::diff_paths(path, base_dir)
                        {
                            let posix_rel_path = to_posix_path(&rel_to_base);
                            matched = include_set_ref.is_match(&rel_to_base)
                                || include_set_ref.is_match(posix_rel_path);
                        }

                        if !matched
                            && let Some(file_name) = path.file_name()
                            && include_set_ref.is_match(file_name)
                        {
                            matched = true;
                        }

                        if matched {
                            let mut excluded = exclude_set_ref.is_match(path)
                                || exclude_set_ref.is_match(to_posix_path(path));
                            if !excluded
                                && let Some(rel_to_base) = pathdiff::diff_paths(path, base_dir)
                                && (exclude_set_ref.is_match(&rel_to_base)
                                    || exclude_set_ref.is_match(to_posix_path(&rel_to_base)))
                            {
                                excluded = true;
                            }

                            if !excluded {
                                let send_path = if cfg!(windows) {
                                    std::fs::canonicalize(path).unwrap_or_else(|_| path.to_owned())
                                } else {
                                    path.to_owned()
                                };
                                let _ = tx.send(send_path);
                            }
                        }
                    }
                }
                ignore::WalkState::Continue
            })
        });
    }

    drop(tx);
    let mut files: Vec<PathBuf> = rx.into_iter().collect();

    files.extend(direct_files);

    files.sort();
    files.dedup();
    files
}

pub fn get_gitignore_matcher(base_dir: &Path) -> ignore::gitignore::Gitignore {
    let mut builder = ignore::gitignore::GitignoreBuilder::new(base_dir);
    let gitignore_path = base_dir.join(".gitignore");
    if gitignore_path.exists() {
        builder.add(gitignore_path);
    }
    builder
        .build()
        .unwrap_or_else(|_| ignore::gitignore::Gitignore::empty())
}

pub fn is_path_ignored(path: &Path, matcher: &ignore::gitignore::Gitignore) -> bool {
    matcher.matched(path, path.is_dir()).is_ignore()
}

pub fn find_package_root(start_path: &Path) -> Option<PathBuf> {
    let mut current = if start_path.is_dir() {
        start_path.to_path_buf()
    } else {
        start_path.parent()?.to_path_buf()
    };

    loop {
        if current.join("package.json").exists() {
            return Some(current);
        }
        if !current.pop() {
            break;
        }
    }
    None
}

/// Helper to compare two paths for equality, handling platform-specific quirks
/// like Windows UNC prefixes and case-insensitivity.
pub fn paths_match(a: Option<&Path>, b: Option<&Path>) -> bool {
    match (a, b) {
        (Some(pa), Some(pb)) => {
            if pa == pb {
                return true;
            }

            #[cfg(windows)]
            {
                let sa = pa.to_string_lossy();
                let sb = pb.to_string_lossy();

                let ca = normalize_windows_path(&sa);
                let cb = normalize_windows_path(&sb);
                return ca.eq_ignore_ascii_case(&cb);
            }

            #[cfg(not(windows))]
            {
                false
            }
        }
        (None, None) => true,
        _ => false,
    }
}

pub fn path_starts_with(path: &Path, prefix: &Path) -> bool {
    if path.starts_with(prefix) {
        return true;
    }

    #[cfg(target_os = "macos")]
    {
        use std::ffi::OsStr;
        let mut p_comps = path.components();
        let mut pre_comps = prefix.components();

        // Skip /private if present in only one of them
        let mut p_first = p_comps.next();
        let mut pre_first = pre_comps.next();

        if let (Some(std::path::Component::RootDir), Some(std::path::Component::RootDir)) =
            (p_first, pre_first)
        {
            p_first = p_comps.next();
            pre_first = pre_comps.next();

            if let (
                Some(std::path::Component::Normal(p_n)),
                Some(std::path::Component::Normal(pre_n)),
            ) = (p_first, pre_first)
            {
                if p_n == OsStr::new("private") && pre_n != OsStr::new("private") {
                    p_first = p_comps.next();
                } else if p_n != OsStr::new("private") && pre_n == OsStr::new("private") {
                    pre_first = pre_comps.next();
                }
            }
        }

        // Compare remaining components
        while let (Some(p_c), Some(pre_c)) = (p_first, pre_first) {
            if p_c != pre_c {
                return false;
            }
            p_first = p_comps.next();
            pre_first = pre_comps.next();
        }

        pre_first.is_none()
    }

    #[cfg(windows)]
    {
        use std::path::Component;
        let mut p_comps = path.components();
        let mut pre_comps = prefix.components();

        loop {
            match (p_comps.next(), pre_comps.next()) {
                (Some(p), Some(pre)) => {
                    let match_comp = match (p, pre) {
                        (Component::Normal(s1), Component::Normal(s2)) => s1
                            .to_string_lossy()
                            .eq_ignore_ascii_case(&s2.to_string_lossy()),
                        (Component::Prefix(p1), Component::Prefix(p2)) => {
                            let normalize_prefix = |kind: std::path::Prefix| {
                                use std::path::Prefix::*;
                                match kind {
                                    VerbatimDisk(d) | Disk(d) => {
                                        format!("{}:", (d as char).to_uppercase())
                                    }
                                    VerbatimUNC(s1, s2) | UNC(s1, s2) => {
                                        format!(
                                            "\\\\{}\\{}",
                                            s1.to_string_lossy(),
                                            s2.to_string_lossy()
                                        )
                                    }
                                    Verbatim(s) | DeviceNS(s) => s.to_string_lossy().to_string(),
                                }
                            };
                            normalize_prefix(p1.kind())
                                .eq_ignore_ascii_case(&normalize_prefix(p2.kind()))
                        }
                        (c1, c2) => c1 == c2,
                    };
                    if !match_comp {
                        return false;
                    }
                }
                (_, None) => return true,
                (None, Some(_)) => return false,
            }
        }
    }

    #[cfg(not(any(target_os = "macos", windows)))]
    {
        false
    }
}

pub fn get_output_path(
    path: &Path,
    base_dir: &Path,
    output_dir: Option<&Path>,
    include_prefix: Option<&Path>,
) -> PathBuf {
    let mut output_path = base_dir.to_path_buf();

    // Canonicalize base_dir and path to handle symlinks (like /tmp -> /private/tmp on macOS)
    let abs_base_dir = base_dir
        .canonicalize()
        .unwrap_or_else(|_| base_dir.to_path_buf());
    let abs_path = path.canonicalize().unwrap_or_else(|_| path.to_path_buf());

    let diff_target = if let Some(prefix) = include_prefix {
        base_dir
            .join(prefix)
            .canonicalize()
            .unwrap_or_else(|_| base_dir.join(prefix))
    } else {
        abs_base_dir
    };

    let rel_path = if let Ok(rel) = abs_path.strip_prefix(&diff_target) {
        rel.to_path_buf()
    } else {
        #[cfg(windows)]
        {
            // Robustly calculate relative path by stripping Windows prefixes if necessary
            let s_abs = abs_path.to_string_lossy();
            let s_target = diff_target.to_string_lossy();

            let clean_abs = normalize_windows_path(&s_abs);
            let clean_target = normalize_windows_path(&s_target);

            pathdiff::diff_paths(&clean_abs, &clean_target).unwrap_or_else(|| abs_path.clone())
        }

        #[cfg(not(windows))]
        {
            pathdiff::diff_paths(&abs_path, &diff_target).unwrap_or_else(|| abs_path.clone())
        }
    };

    if let Some(out_dir) = output_dir {
        output_path.push(out_dir);
        output_path.push(rel_path);
    } else {
        output_path.push(rel_path);
    }

    output_path.set_extension("codegen.ts");
    output_path
}

pub fn merge_schema_texts(texts: &[String]) -> String {
    let total_len: usize = texts.iter().map(|s| s.len() + 1).sum();
    let mut merged = String::with_capacity(total_len);
    let mut seen_base = ahash::AHashSet::default();
    let mut seen_schema = false;
    let mut seen_root_op_names = ahash::AHashSet::default();

    let mut parser = tree_sitter::Parser::new();
    let language: tree_sitter::Language = tree_sitter_graphql::LANGUAGE.into();
    if let Err(e) = parser.set_language(&language) {
        eprintln!(
            "{}: Failed to set GraphQL language: {}",
            "ERROR".red(),
            e.to_string().red()
        );
        for text in texts {
            merged.push_str(text);
            merged.push('\n');
        }
        return merged;
    }

    let query = crate::queries::GQL_MERGE_QUERY_CACHE.get_or_init(|| {
        tree_sitter::Query::new(&language, crate::queries::GQL_MERGE_QUERY).unwrap()
    });
    let name_idx = query.capture_index_for_name("name").unwrap();
    let type_def_idx = query.capture_index_for_name("type_def").unwrap();
    let schema_def_idx = query.capture_index_for_name("schema_def").unwrap();
    let operation_idx = query.capture_index_for_name("operation").unwrap();
    let named_type_idx = query.capture_index_for_name("named_type").unwrap();
    let root_op_idx = query.capture_index_for_name("root_op").unwrap();
    let mut cursor = tree_sitter::QueryCursor::new();

    for text in texts {
        let tree = if let Some(t) = parser.parse(text, None) {
            t
        } else {
            merged.push_str(text);
            merged.push('\n');
            continue;
        };
        let root = tree.root_node();

        // One pass to collect all info
        let mut collected_matches = Vec::new();
        {
            let mut matches_iter = cursor.matches(query, root, text.as_bytes());
            while let Some(m) = matches_iter.next() {
                let mut name_node = None;
                let mut container_node = None;
                let mut is_schema_def = false;
                let mut is_root_op = false;
                let mut operation_node = None;
                let mut named_type_node = None;

                for cap in m.captures {
                    if cap.index == name_idx {
                        name_node = Some(cap.node);
                    } else if cap.index == type_def_idx {
                        container_node = Some(cap.node);
                    } else if cap.index == schema_def_idx {
                        is_schema_def = true;
                    } else if cap.index == root_op_idx {
                        is_root_op = true;
                    } else if cap.index == operation_idx {
                        operation_node = Some(cap.node);
                    } else if cap.index == named_type_idx {
                        named_type_node = Some(cap.node);
                    }
                }

                if let Some(container) = container_node {
                    collected_matches.push((
                        container,
                        is_schema_def,
                        is_root_op,
                        name_node,
                        operation_node,
                        named_type_node,
                    ));
                }
            }
        }

        let mut modifications = Vec::new();
        let mut schema_block_indices = Vec::new();

        // Map root ops to their containing schema blocks
        for (idx, (container, is_schema, _, _, _, _)) in collected_matches.iter().enumerate() {
            if *is_schema {
                schema_block_indices.push((
                    idx,
                    container.start_byte(),
                    container.end_byte(),
                    Vec::new(),
                ));
            }
        }

        for (idx, (container, _, is_root_op, _, _, _)) in collected_matches.iter().enumerate() {
            if *is_root_op {
                for block in schema_block_indices.iter_mut() {
                    if container.start_byte() >= block.1 && container.end_byte() <= block.2 {
                        block.3.push(idx);
                        break;
                    }
                }
            }
        }

        let mut root_ops_to_remove = ahash::AHashSet::default();
        let mut handled_schema_blocks = ahash::AHashSet::default();

        for (m_idx, (container, is_schema, is_root_op, name_node, _op_node, _ty_node)) in
            collected_matches.iter().enumerate()
        {
            if *is_schema {
                if handled_schema_blocks.contains(&m_idx) {
                    continue;
                }

                let block = schema_block_indices.iter().find(|b| b.0 == m_idx).unwrap();
                let mut unique_ops_in_block = Vec::new();
                for &r_idx in &block.3 {
                    let (_, _, _, _, o_n, _t_n) = &collected_matches[r_idx];
                    if let Some(o_n) = o_n {
                        let op = text[o_n.start_byte()..o_n.end_byte()].to_string();
                        if !seen_root_op_names.contains(&op) {
                            unique_ops_in_block.push(r_idx);
                        } else {
                            root_ops_to_remove.insert(r_idx);
                        }
                    }
                }

                if unique_ops_in_block.is_empty() && !block.3.is_empty() {
                    // Entire schema block is redundant
                    modifications.push((
                        container.start_byte(),
                        container.end_byte(),
                        "".to_string(),
                    ));
                } else if seen_schema {
                    // Convert to extend schema
                    modifications.push((
                        container.start_byte(),
                        container.start_byte() + 6,
                        "extend schema".to_string(),
                    ));
                    for &r_idx in &unique_ops_in_block {
                        let (_, _, _, _, o_n, _t_n) = &collected_matches[r_idx];
                        let op =
                            text[o_n.unwrap().start_byte()..o_n.unwrap().end_byte()].to_string();
                        seen_root_op_names.insert(op);
                    }
                } else {
                    seen_schema = true;
                    for &r_idx in &unique_ops_in_block {
                        let (_, _, _, _, o_n, _t_n) = &collected_matches[r_idx];
                        let op =
                            text[o_n.unwrap().start_byte()..o_n.unwrap().end_byte()].to_string();
                        seen_root_op_names.insert(op);
                    }
                }
                handled_schema_blocks.insert(m_idx);
            } else if *is_root_op {
                if root_ops_to_remove.contains(&m_idx) {
                    modifications.push((
                        container.start_byte(),
                        container.end_byte(),
                        "".to_string(),
                    ));
                }
            } else if let Some(name_node) = name_node {
                let name = &text[name_node.start_byte()..name_node.end_byte()];
                let is_extension = container.kind() == "type_extension";

                if !is_extension {
                    if seen_base.contains(name) {
                        let is_scalar = container.kind() == "scalar_type_definition";
                        let mut has_directives = false;
                        let mut cursor = container.walk();
                        for child in container.children(&mut cursor) {
                            if child.kind() == "directives" {
                                has_directives = true;
                                break;
                            }
                        }

                        if is_scalar && !has_directives {
                            modifications.push((
                                container.start_byte(),
                                container.end_byte(),
                                "".to_string(),
                            ));
                        } else {
                            let mut insert_pos = container.start_byte();
                            let mut cursor = container.walk();
                            for child in container.children(&mut cursor) {
                                let kind = child.kind();
                                if kind != "description" && kind != "comment" {
                                    insert_pos = child.start_byte();
                                    break;
                                }
                            }
                            modifications.push((
                                container.start_byte(),
                                insert_pos,
                                "extend ".to_string(),
                            ));
                        }
                    } else {
                        seen_base.insert(name.to_string());
                    }
                }
            }
        }

        modifications.sort_by_key(|m| m.0);
        let mut current_pos = 0;
        for (start, end, replacement) in modifications {
            if start < current_pos {
                continue;
            }
            merged.push_str(&text[current_pos..start]);
            merged.push_str(&replacement);
            current_pos = end;
        }
        merged.push_str(&text[current_pos..]);
        merged.push('\n');
    }

    merged
}

/// Simple interpolation masker for template strings.
/// Replaces ${...} with spaces of the same length to preserve offsets.
pub fn mask_interpolations(text: &str) -> std::borrow::Cow<'_, str> {
    if !text.contains("${") {
        return std::borrow::Cow::Borrowed(text);
    }

    let mut result = String::with_capacity(text.len());
    let mut chars = text.chars().peekable();

    while let Some(c) = chars.next() {
        if c == '$' && chars.peek() == Some(&'{') {
            result.push_str("  ");
            chars.next(); // consume '{'
            let mut depth = 1;
            while depth > 0 {
                if let Some(inner_c) = chars.next() {
                    match inner_c {
                        '{' => {
                            depth += 1;
                            result.push(' ');
                        }
                        '}' => {
                            depth -= 1;
                            result.push(' ');
                        }
                        '\n' => result.push('\n'),
                        _ => result.push(' '),
                    }
                } else {
                    break;
                }
            }
        } else {
            result.push(c);
        }
    }
    std::borrow::Cow::Owned(result)
}

/// Finds the range of an operation definition by name
pub fn find_operation_range(doc: &DocumentState, operation_name: &str) -> Option<Range> {
    for block in doc.get_graphql_trees() {
        let query = GQL_SYMBOL_QUERY_CACHE.get_or_init(|| {
            let lang = tree_sitter_graphql::LANGUAGE.into();
            tree_sitter::Query::new(&lang, GQL_SYMBOL_QUERY).unwrap()
        });

        let mut cursor = tree_sitter::QueryCursor::new();
        let mut matches =
            cursor.matches(query, block.tree.root_node(), |node: tree_sitter::Node| {
                doc.rope
                    .byte_slice(
                        (node.start_byte() + block.offset)..(node.end_byte() + block.offset),
                    )
                    .chunks()
            });

        while let Some(m) = matches.next() {
            let mut name = None;
            let mut op_node = None;

            for cap in m.captures {
                let cap_name = query.capture_names()[cap.index as usize];
                if cap_name == "symbol.name" {
                    name = Some(doc.get_node_text(cap.node, block.offset));
                    op_node = Some(cap.node);
                }
            }

            if let (Some(n), Some(node)) = (name, op_node)
                && n == operation_name
            {
                return Some(doc.translate_to_file_range(node, block.offset));
            }
        }
    }

    None
}

pub fn push_duplicate_operation_diagnostic(
    diagnostics: &mut Vec<Diagnostic>,
    range: Range,
    name: &str,
    other_files: Option<Vec<String>>,
) {
    let message = if let Some(files) = other_files {
        format!(
            "Duplicate operation name '{}' (also in: {})",
            name,
            files.join(", ")
        )
    } else {
        format!("Duplicate operation name '{}'", name)
    };

    diagnostics.push(Diagnostic {
        range,
        severity: Some(DiagnosticSeverity::ERROR),
        message,
        code: Some(NumberOrString::String("duplicate_operation".to_string())),
        source: DIAGNOSTIC_SOURCE.map(String::from),
        ..Default::default()
    });
}

pub fn to_posix_path(path: &Path) -> String {
    let s = path.to_string_lossy();
    if cfg!(windows) {
        normalize_windows_path(&s).replace('\\', "/")
    } else {
        s.into_owned()
    }
}

pub fn normalize_uri(uri: Url) -> Url {
    if let Ok(path) = uri.to_file_path() {
        // Try to canonicalize to resolve symlinks
        let path = std::fs::canonicalize(&path).unwrap_or(path);
        let path_str = path.to_string_lossy();

        #[cfg(windows)]
        let path_str = normalize_windows_path(&path_str);

        return Url::from_file_path(Path::new(&*path_str)).unwrap_or(uri);
    }
    uri
}

pub fn normalize_line_endings(text: &str) -> String {
    text.replace("\r\n", "\n")
}

pub fn normalize_windows_path(s: &str) -> String {
    let s = if let Some(stripped) = s.strip_prefix(r"\\?\UNC\") {
        format!("\\\\{}", stripped)
    } else if let Some(stripped) = s.strip_prefix(r"\\?\") {
        stripped.to_string()
    } else {
        s.to_string()
    };

    // Replace all forward slashes with backslashes for consistency before processing
    let mut s = s.replace('/', "\\");

    // Handle drive letter casing: "c:\" -> "C:\"
    if s.len() >= 2 && s.as_bytes()[1] == b':' {
        let drive = s.as_bytes()[0] as char;
        if drive.is_ascii_lowercase() {
            s = format!("{}{}", drive.to_ascii_uppercase(), &s[1..]);
        }
    }

    s
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    #[ntest::timeout(3000)]
    fn test_merge_schema_texts_multiple_schema_blocks() {
        let schema1 = "schema { query: Query } type Query { foo: String }".to_string();
        let schema2 = "schema { query: Query } type Query { bar: String }".to_string();
        let merged = merge_schema_texts(&[schema1, schema2]);
        assert!(merged.contains("schema { query: Query }"));
        assert!(!merged.contains("extend schema { query: Query }")); // should be removed as redundant
        assert!(merged.contains("type Query { foo: String }"));
        assert!(merged.contains("extend type Query { bar: String }"));
    }

    #[test]
    #[ntest::timeout(3000)]
    fn test_merge_schema_texts_multiple_query() {
        let schema1 = "type Query { foo: String }".to_string();
        let schema2 = "type Query { bar: String }".to_string();
        let merged = merge_schema_texts(&[schema1, schema2]);
        assert!(merged.contains("type Query { foo: String }"));
        assert!(merged.contains("extend type Query { bar: String }"));

        // Verify with apollo-compiler
        let s = apollo_compiler::Schema::parse(&merged, "merged.graphql").expect("Parsing failed");
        s.validate().expect("Validation failed");
    }

    #[test]
    #[ntest::timeout(3000)]
    fn test_merge_schema_texts_conflicting_root_names() {
        let schema1 = "schema { query: Q1 } type Q1 { f1: String }".to_string();
        let schema2 = "schema { query: Q2 } type Q2 { f2: String }".to_string();
        let merged = merge_schema_texts(&[schema1, schema2]);

        println!("Merged:\n{}", merged);
        assert!(merged.contains("schema { query: Q1 }"));
        assert!(!merged.contains("extend schema { query: Q2 }"));
        assert!(!merged.contains("schema { query: Q2 }"));
        assert!(merged.contains("type Q2 { f2: String }"));

        let s = apollo_compiler::Schema::parse(&merged, "merged.graphql").expect("Parsing failed");
        s.validate().expect("Validation failed after fix");
    }

    #[test]
    #[ntest::timeout(100)]
    fn test_mask_interpolations() {
        let input = "query { user(id: ${userId}) { name } }";
        let masked = mask_interpolations(input);
        assert_eq!(masked.len(), input.len());
        assert!(masked.contains("user(id: "));
        assert!(masked.contains(") { name }"));

        let nested = "query { user(id: ${getId({a: 1})}) { name } }";
        let masked_nested = mask_interpolations(nested);
        assert_eq!(masked_nested.len(), nested.len());

        let multi_line = "query {\n  ${fragment}\n  user { id }\n}";
        let masked_multi_line = mask_interpolations(multi_line);
        assert_eq!(masked_multi_line.len(), multi_line.len());
        assert_eq!(
            masked_multi_line.lines().count(),
            multi_line.lines().count()
        );
    }

    #[test]
    #[ntest::timeout(3000)]
    fn test_get_glob_root() {
        assert_eq!(get_glob_root("src/*.ts"), PathBuf::from("src"));
        assert_eq!(
            get_glob_root("src/components/**/*.tsx"),
            PathBuf::from("src/components")
        );
        assert_eq!(get_glob_root("*.graphql"), PathBuf::from(""));
        assert_eq!(get_glob_root("docs/"), PathBuf::from("docs/"));
    }

    #[test]
    fn test_path_starts_with() {
        let path = Path::new("/Users/foo/bar/baz.ts");
        let prefix = Path::new("/Users/foo");
        assert!(path_starts_with(path, prefix));

        let path = Path::new("/private/Users/foo/bar/baz.ts");
        let prefix = Path::new("/Users/foo");
        #[cfg(target_os = "macos")]
        assert!(path_starts_with(path, prefix));
        #[cfg(not(target_os = "macos"))]
        assert!(!path_starts_with(path, prefix));

        let path = Path::new("/Users/foo/bar/baz.ts");
        let prefix = Path::new("/private/Users/foo");
        #[cfg(target_os = "macos")]
        assert!(path_starts_with(path, prefix));

        let path = Path::new("/Users/foo/bar/baz.ts");
        let prefix = Path::new("/Users/fo");
        assert!(!path_starts_with(path, prefix));
    }
}
