use crate::Config;
use crate::backend::validation::push_duplicate_operation_diagnostic;
use crate::document::DocumentState;
use crate::queries::*;
use crate::utils::mask_interpolations;
use apollo_compiler::Schema;
use tower_lsp::lsp_types::*;
use tree_sitter::{Node, QueryCursor, StreamingIterator};

mod fragments;
mod operations;
mod selection_set;
mod values;

pub(super) struct ValidationContext<'a> {
    pub schema: &'a apollo_compiler::validation::Valid<Schema>,
    pub all_fragments: &'a [crate::features::completion::FragmentCompletionInfo],
    pub used_fragments: Option<&'a fnv::FnvHashSet<String>>,
    pub used_variables: fnv::FnvHashSet<String>,
    pub defined_variables: fnv::FnvHashSet<String>,
    pub diagnostics: &'a mut Vec<Diagnostic>,
    pub config: Option<&'a Config>,
    pub include_ignored: bool,
    pub workspace_loaded: bool,
    pub is_operation: bool,
    pub selected_fields: fnv::FnvHashSet<String>,
    pub current_operation_type: Option<String>,
}

impl DocumentState {
    pub fn get_semantic_diagnostics(
        &self,
        valid_schema: &apollo_compiler::validation::Valid<Schema>,
        all_fragments: &[crate::features::completion::FragmentCompletionInfo],
        used_fragments: Option<&fnv::FnvHashSet<String>>,
        config: Option<&Config>,
        verbose: bool,
        workspace_loaded: bool,
    ) -> Vec<Diagnostic> {
        let mut diagnostics = Vec::new();

        let blocks = self.get_graphql_trees();

        for block in blocks {
            let offset = block.offset;
            // 1. Syntax errors from Tree-sitter
            self.collect_gql_errors(block.tree.root_node(), offset, &mut diagnostics);

            // 2. Parser/Validation errors from apollo-compiler
            let block_text = self.get_node_text(block.tree.root_node(), offset);
            let masked = mask_interpolations(&block_text);

            let doc_res = apollo_compiler::executable::ExecutableDocument::parse(
                valid_schema,
                &masked,
                self.uri.as_str(),
            );
            if let Err(with_errors) = doc_res {
                // Only report parser errors if they are not about schema definitions in executable docs
                // (because the tool currently scans schema files too)
                let reportable_errors: Vec<_> = with_errors
                    .errors
                    .iter()
                    .filter(|e| !e.to_string().contains("must not contain"))
                    .collect();

                if !reportable_errors.is_empty() {
                    // If apollo-compiler reports errors that are actually semantic (like missing fields
                    // or duplicate operations) we suppress those here in favor of our own deterministic
                    // diagnostics generated by the manual validation pass below. Detect common patterns
                    // and skip reporting them as parse errors.
                    let mut skip_reporting = false;
                    if let Some(first_err) = reportable_errors.first() {
                        let s = first_err.to_string();
                        if s.contains("does not have a field")
                            || s.contains("defined multiple times")
                            || s.contains("is defined multiple times")
                        {
                            skip_reporting = true;
                        }
                    }

                    if !skip_reporting {
                        diagnostics.push(Diagnostic {
                            range: self.translate_to_file_range(block.tree.root_node(), offset),
                            severity: Some(DiagnosticSeverity::ERROR),
                            message: format!("GraphQL Parse Error: {}", with_errors.errors),
                            ..Default::default()
                        });
                    }
                }
            }

            // 3. Our manual schema validation (handles fragments across files)
            let mut ctx = ValidationContext {
                schema: valid_schema,
                all_fragments,
                used_fragments,
                used_variables: fnv::FnvHashSet::default(),
                defined_variables: fnv::FnvHashSet::default(),
                diagnostics: &mut diagnostics,
                config,
                include_ignored: verbose,
                workspace_loaded,
                is_operation: false,
                selected_fields: fnv::FnvHashSet::default(),
                current_operation_type: None,
            };

            self.validate_tree(block.tree.root_node(), offset, &mut ctx);
        }

        // After validating tree nodes, optionally run cross-operation checks within this document.
        if let Some(cfg) = config {
            if let Some(rules) = &cfg.rules {
                if let Some(true) = rules.unique_operation_name {
                    // Detect duplicate operation names within this document and report diagnostics.
                    use std::collections::HashMap;
                    let mut counts: HashMap<String, usize> = HashMap::new();
                    for op in &self.operations {
                        if let Some(name) = &op.name {
                            *counts.entry(name.clone()).or_insert(0) += 1;
                        }
                    }

                    for (name, cnt) in counts.into_iter() {
                        if cnt > 1 {
                            // point the diagnostic at the last occurrence of the operation name in the document
                            let text = self.rope.to_string();
                            if let Some(start_byte) = text.rfind(&name) {
                                let end_byte = start_byte + name.len();
                                let range = Range {
                                    start: self.byte_to_position(start_byte),
                                    end: self.byte_to_position(end_byte),
                                };
                                // Use shared helper to push diagnostic (keeps message/code consistent)
                                push_duplicate_operation_diagnostic(
                                    &mut diagnostics,
                                    range,
                                    &name,
                                    None,
                                );
                            }
                        }
                    }
                }
            }
        }

        diagnostics
    }

    fn validate_tree(&self, node: Node, offset: usize, ctx: &mut ValidationContext) {
        let query = GQL_DIAGNOSTICS_QUERY_CACHE.get_or_init(|| {
            let lang = tree_sitter_graphql::LANGUAGE.into();
            tree_sitter::Query::new(&lang, GQL_DIAGNOSTICS_QUERY).unwrap()
        });

        let mut cursor = QueryCursor::new();
        let mut matches = cursor.matches(query, node, |n: Node| {
            let start = n.start_byte();
            let end = n.end_byte();
            self.rope
                .byte_slice((start + offset)..(end + offset))
                .chunks()
        });

        while let Some(m) = matches.next() {
            for cap in m.captures {
                let capture_name = query.capture_names()[cap.index as usize];
                if capture_name == "operation" {
                    self.validate_operation(cap.node, offset, ctx);
                } else if capture_name == "fragment" {
                    self.validate_fragment(cap.node, offset, ctx, 0);
                }
            }
        }
    }

    pub(super) fn is_deprecation_ignored(&self, reason: &str, config: Option<&Config>) -> bool {
        if let Some(cfg) = config
            && let Some(patterns) = &cfg.ignore_deprecations
        {
            for p in patterns {
                if let Ok(re) = regex::Regex::new(p)
                    && re.is_match(reason)
                {
                    return true;
                }
            }
        }
        false
    }

    pub(super) fn add_deprecation_diagnostic(
        &self,
        ctx: &mut ValidationContext,
        node: Node,
        offset: usize,
        message: String,
        reason: &str,
    ) {
        if !self.is_deprecation_ignored(reason, ctx.config) {
            ctx.diagnostics.push(Diagnostic {
                range: self.translate_to_file_range(node, offset),
                severity: Some(DiagnosticSeverity::WARNING),
                message,
                ..Default::default()
            });
        } else if ctx.include_ignored {
            ctx.diagnostics.push(Diagnostic {
                range: self.translate_to_file_range(node, offset),
                severity: Some(DiagnosticSeverity::INFORMATION),
                message: format!("[Ignored] {}", message),
                ..Default::default()
            });
        }
    }

    fn collect_gql_errors(
        &self,
        root: tree_sitter::Node,
        offset_byte: usize,
        diagnostics: &mut Vec<Diagnostic>,
    ) {
        let mut stack = vec![root];
        while let Some(node) = stack.pop() {
            if node.is_error() || node.is_missing() {
                let range = self.translate_to_file_range(node, offset_byte);

                diagnostics.push(Diagnostic {
                    range,
                    severity: Some(DiagnosticSeverity::ERROR),
                    message: format!("GraphQL Syntax Error: unexpected '{}'", node.kind()),
                    ..Default::default()
                });
            }

            let mut cursor = node.walk();
            for child in node.children(&mut cursor) {
                stack.push(child);
            }
        }
    }
}
